name: Deploy docs
on: [push]

runs:
  on: [ubuntu-latest]

  - name: Send dispatch
    run: |
      curl -L \
      -X POST \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer ${{secrets.PAGES_DEPLOY}}"\
      -H "X-GitHub-Api-Version: 2022-11-28" \
      https://api.github.com/repos/DryByte/drybyte.github.io/dispatches \
      -d '{"event_type":"on-demand-test","client_payload":{"unit":false,"integration":true}}'